version: '3'
services:
    opendatabr:
        image: postgres:9.5
        volumes:
            - ./bin/postgresql:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_MULTIPLE_DATABASES=opendatabr,opendatabr_test
            - POSTGRES_USER=opendata
            - POSTGRES_PASSWORD=opendata
        ports:
            - "5432:5432"

